// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/mensaje.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nombre_Estado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Last   string `protobuf:"bytes,2,opt,name=last,proto3" json:"last,omitempty"`
	Estate string `protobuf:"bytes,3,opt,name=estate,proto3" json:"estate,omitempty"`
}

func (x *Nombre_Estado) Reset() {
	*x = Nombre_Estado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mensaje_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nombre_Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nombre_Estado) ProtoMessage() {}

func (x *Nombre_Estado) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensaje_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nombre_Estado.ProtoReflect.Descriptor instead.
func (*Nombre_Estado) Descriptor() ([]byte, []int) {
	return file_proto_mensaje_proto_rawDescGZIP(), []int{0}
}

func (x *Nombre_Estado) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Nombre_Estado) GetLast() string {
	if x != nil {
		return x.Last
	}
	return ""
}

func (x *Nombre_Estado) GetEstate() string {
	if x != nil {
		return x.Estate
	}
	return ""
}

type Nombre_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Last string `protobuf:"bytes,2,opt,name=last,proto3" json:"last,omitempty"`
	Id   int32  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Nombre_ID) Reset() {
	*x = Nombre_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mensaje_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nombre_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nombre_ID) ProtoMessage() {}

func (x *Nombre_ID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensaje_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nombre_ID.ProtoReflect.Descriptor instead.
func (*Nombre_ID) Descriptor() ([]byte, []int) {
	return file_proto_mensaje_proto_rawDescGZIP(), []int{1}
}

func (x *Nombre_ID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Nombre_ID) GetLast() string {
	if x != nil {
		return x.Last
	}
	return ""
}

func (x *Nombre_ID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Nombre struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Last string `protobuf:"bytes,2,opt,name=last,proto3" json:"last,omitempty"`
}

func (x *Nombre) Reset() {
	*x = Nombre{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mensaje_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nombre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nombre) ProtoMessage() {}

func (x *Nombre) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensaje_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nombre.ProtoReflect.Descriptor instead.
func (*Nombre) Descriptor() ([]byte, []int) {
	return file_proto_mensaje_proto_rawDescGZIP(), []int{2}
}

func (x *Nombre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Nombre) GetLast() string {
	if x != nil {
		return x.Last
	}
	return ""
}

type ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ID) Reset() {
	*x = ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mensaje_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensaje_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_proto_mensaje_proto_rawDescGZIP(), []int{3}
}

func (x *ID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Estado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estate int32 `protobuf:"varint,1,opt,name=estate,proto3" json:"estate,omitempty"`
}

func (x *Estado) Reset() {
	*x = Estado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mensaje_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estado) ProtoMessage() {}

func (x *Estado) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensaje_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estado.ProtoReflect.Descriptor instead.
func (*Estado) Descriptor() ([]byte, []int) {
	return file_proto_mensaje_proto_rawDescGZIP(), []int{4}
}

func (x *Estado) GetEstate() int32 {
	if x != nil {
		return x.Estate
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mensaje_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensaje_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_mensaje_proto_rawDescGZIP(), []int{5}
}

type Personas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status []*Nombre_Estado `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
}

func (x *Personas) Reset() {
	*x = Personas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mensaje_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Personas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Personas) ProtoMessage() {}

func (x *Personas) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensaje_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Personas.ProtoReflect.Descriptor instead.
func (*Personas) Descriptor() ([]byte, []int) {
	return file_proto_mensaje_proto_rawDescGZIP(), []int{6}
}

func (x *Personas) GetStatus() []*Nombre_Estado {
	if x != nil {
		return x.Status
	}
	return nil
}

type Mensaje struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *Mensaje) Reset() {
	*x = Mensaje{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mensaje_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mensaje) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mensaje) ProtoMessage() {}

func (x *Mensaje) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensaje_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mensaje.ProtoReflect.Descriptor instead.
func (*Mensaje) Descriptor() ([]byte, []int) {
	return file_proto_mensaje_proto_rawDescGZIP(), []int{7}
}

func (x *Mensaje) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_proto_mensaje_proto protoreflect.FileDescriptor

var file_proto_mensaje_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x4f, 0x0a, 0x0d, 0x4e,
	0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6c, 0x61, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x43, 0x0a, 0x09,
	0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x30, 0x0a, 0x06, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x61, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x06, 0x45, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x37, 0x0a, 0x08, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x73,
	0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x45,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x23, 0x0a,
	0x07, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73,
	0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61,
	0x6a, 0x65, 0x32, 0xf0, 0x02, 0x0a, 0x09, 0x46, 0x75, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73,
	0x12, 0x36, 0x0a, 0x12, 0x41, 0x67, 0x72, 0x65, 0x67, 0x61, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x6f, 0x4f, 0x4d, 0x53, 0x12, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4e, 0x6f,
	0x6d, 0x62, 0x72, 0x65, 0x5f, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x1a, 0x0b, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x39, 0x0a, 0x19, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x72, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x6e, 0x6f, 0x64, 0x65, 0x31, 0x12, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x5f, 0x49, 0x44, 0x1a, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x39, 0x0a, 0x19, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72,
	0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x32,
	0x12, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x49,
	0x44, 0x1a, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x28,
	0x0a, 0x0e, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x73,
	0x12, 0x08, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x44, 0x1a, 0x0c, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x2d, 0x0a, 0x0d, 0x4f, 0x62, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x43, 0x69, 0x66, 0x72, 0x61, 0x73, 0x12, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x73, 0x12, 0x2e, 0x0a, 0x0e, 0x4f, 0x62, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x43, 0x69, 0x66, 0x72, 0x61, 0x73, 0x32, 0x12, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x1a, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x12, 0x2c, 0x0a, 0x0e, 0x4f, 0x62, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x43, 0x69, 0x66, 0x72, 0x61, 0x73, 0x33, 0x12, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x1a, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x69, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x73, 0x2d, 0x44, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x69, 0x64, 0x6f, 0x73, 0x2d, 0x32, 0x30, 0x32, 0x33, 0x2d, 0x30,
	0x32, 0x2f, 0x47, 0x72, 0x75, 0x70, 0x6f, 0x33, 0x31, 0x2d, 0x4c, 0x61, 0x62, 0x6f, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x69, 0x6f, 0x2d, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mensaje_proto_rawDescOnce sync.Once
	file_proto_mensaje_proto_rawDescData = file_proto_mensaje_proto_rawDesc
)

func file_proto_mensaje_proto_rawDescGZIP() []byte {
	file_proto_mensaje_proto_rawDescOnce.Do(func() {
		file_proto_mensaje_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mensaje_proto_rawDescData)
	})
	return file_proto_mensaje_proto_rawDescData
}

var file_proto_mensaje_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_mensaje_proto_goTypes = []interface{}{
	(*Nombre_Estado)(nil), // 0: grpc.Nombre_Estado
	(*Nombre_ID)(nil),     // 1: grpc.Nombre_ID
	(*Nombre)(nil),        // 2: grpc.Nombre
	(*ID)(nil),            // 3: grpc.ID
	(*Estado)(nil),        // 4: grpc.Estado
	(*Empty)(nil),         // 5: grpc.Empty
	(*Personas)(nil),      // 6: grpc.Personas
	(*Mensaje)(nil),       // 7: grpc.Mensaje
}
var file_proto_mensaje_proto_depIdxs = []int32{
	0, // 0: grpc.Personas.status:type_name -> grpc.Nombre_Estado
	0, // 1: grpc.Funciones.AgregarRegistroOMS:input_type -> grpc.Nombre_Estado
	1, // 2: grpc.Funciones.RegistrarNombresDatanode1:input_type -> grpc.Nombre_ID
	1, // 3: grpc.Funciones.RegistrarNombresDatanode2:input_type -> grpc.Nombre_ID
	3, // 4: grpc.Funciones.ObtenerNombres:input_type -> grpc.ID
	4, // 5: grpc.Funciones.ObtenerCifras:input_type -> grpc.Estado
	7, // 6: grpc.Funciones.ObtenerCifras2:input_type -> grpc.Mensaje
	7, // 7: grpc.Funciones.ObtenerCifras3:input_type -> grpc.Mensaje
	5, // 8: grpc.Funciones.AgregarRegistroOMS:output_type -> grpc.Empty
	5, // 9: grpc.Funciones.RegistrarNombresDatanode1:output_type -> grpc.Empty
	5, // 10: grpc.Funciones.RegistrarNombresDatanode2:output_type -> grpc.Empty
	2, // 11: grpc.Funciones.ObtenerNombres:output_type -> grpc.Nombre
	6, // 12: grpc.Funciones.ObtenerCifras:output_type -> grpc.Personas
	7, // 13: grpc.Funciones.ObtenerCifras2:output_type -> grpc.Mensaje
	5, // 14: grpc.Funciones.ObtenerCifras3:output_type -> grpc.Empty
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_mensaje_proto_init() }
func file_proto_mensaje_proto_init() {
	if File_proto_mensaje_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mensaje_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nombre_Estado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mensaje_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nombre_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mensaje_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nombre); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mensaje_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mensaje_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Estado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mensaje_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mensaje_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Personas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mensaje_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mensaje); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mensaje_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mensaje_proto_goTypes,
		DependencyIndexes: file_proto_mensaje_proto_depIdxs,
		MessageInfos:      file_proto_mensaje_proto_msgTypes,
	}.Build()
	File_proto_mensaje_proto = out.File
	file_proto_mensaje_proto_rawDesc = nil
	file_proto_mensaje_proto_goTypes = nil
	file_proto_mensaje_proto_depIdxs = nil
}
